# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 945b187f60a824012efd0979799758a25805859b5e72ad86aa9dfb47c076b4a7a45192417dca1710c44c2ceff4cecfd599dbb510d327a0f3206f65c64a87c4ee

test:
  secret_key_base: 4ca1c497f1c9643f90b87a3e60c5cbc0033eb96d567f166c5725bf2984238141eead51b4add657177efa3f40a1be5822987e9aa20abe757e6f60de48dad89d2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
