# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1fdcd93193bb2eebc2587e6b925da22c511cc072743d4fbcc208988294081897aff8269d907a3ff5297c6adbbea0073b3a8ab0d328785498046d77d2bd4babf

test:
  secret_key_base: 1d7c223f66bb060ca158c68f30cd235a72bb908685fad78be9a60f59ff60fdfe8e44b82da49120a1ada76b123f97d67d9551733c966d74249971fc2cd65de69d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
